
spring:
  kafka:
    bootstrap-servers: 192.168.6.233:9092,192.168.6.236:9092,192.168.6.238:9092
    consumer:
      group-id: sink01
      auto-commit-interval: 1000
      enable-auto-commit: true
server:
  port: 13579
kafka:
  odps:
    consumer:
      threads: 10
